### ISSUE TITLE
Test play with twitter app (non-retina device)

### ISSUE THREAD

**Issue by livlab** [livlab/ias-bingo#10]
Android or iOS, doesn't matter
- [x] request a card
- [x] submit 1 photo with the wrong hashtag (not on your card)
- [x] submit 5 consecutive photos with hashtag to make bingo from that card
- [x] verify messages received from bot after each action
- [x] verify updates to leaderboard page after each action
- [ ] erase all tweets and images
- [ ] erase play in DB

**Comment by livlab** [comment]
Card appeared http://iasbingo.com/card/livlab within seconds of tweeting @iasbingo https://twitter.com/livlab/status/588441428650397698, but no tweet back with card link.

**Comment by livlab** [comment]
Box filled in card within seconds of tweeting @iasbingo https://twitter.com/livlab/status/588442436571017216

**Comment by livlab** [comment]
Submitting photo with wrong hashtag did not produce any response from @iasbingo

**Comment by livlab** [comment]
Leaderboard updating as expected after each submission
![screenshot 2015-04-15 16 48 09](https://cloud.githubusercontent.com/assets/1936365/7168975/47d19a70-e38f-11e4-9774-5fecda2b1a8d.png)

**Comment by livlab** [comment]
Leaderboard status changed to Bingo once Bingo has been accomplished.

**Comment by livlab** [comment]
Tested with Android App.

**Comment by tpitale** [comment]
This is the error I'm seeing on the server:

```
Traceback (most recent call last):
  File "daemon.py", line 294, in doTweet
    InputTweet(tweet)
  File "daemon.py", line 190, in __init__
    self.sendReply("Congratulations, that's Bingo! You're welcome to keep going...")
  File "daemon.py", line 248, in sendReply
    img_data = self.user_card.renderCard()
  File "daemon.py", line 141, in renderCard
    subprocess.call(["phantomjs", "rasterize.js", "http://localhost:5000/card/"+self.user['screen_name']+"?fortwitter", "foo.png", "750px*870px"])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I'll investigate further.

**Comment by tpitale** [comment]
Missing phantomjs. PR here: https://github.com/livlab/ias-bingo/pull/29

**Comment by tpitale** [comment]
Tweeting from iOS through tweetbot works.

**Comment by tpitale** [comment]
Latest error after phantomjs install:

```
Traceback (most recent call last):
  File "daemon.py", line 294, in doTweet
    InputTweet(tweet)
  File "daemon.py", line 194, in __init__
    self.sendReply("Nice #%s! Check this out: %s"%(tagged_goal,goal_story))
  File "daemon.py", line 248, in sendReply
    img_data = self.user_card.renderCard()
  File "daemon.py", line 142, in renderCard
    with open("foo.png") as fh:
IOError: [Errno 2] No such file or directory: 'foo.png'
```

**Comment by tpitale** [comment]
PR fix for this at #30.

**Comment by tpitale** [comment]
Let me know when you merge those two and I'll update the server. Be back online soon.

**Comment by livlab** [comment]
Ok, both merged.

**Comment by tpitale** [comment]
Test again whenever you're ready!

**Comment by tpitale** [comment]
Now seeing:

```
Traceback (most recent call last):
  File "daemon.py", line 293, in doTweet
    InputTweet(tweet)
  File "daemon.py", line 168, in __init__
    self.sendReply("Thanks for playing!")
  File "daemon.py", line 255, in sendReply
    print twit.statuses.update_with_media(**{"status":status,"in_reply_to_status_id":id_str,"media[]":img_data})
  File "/u/apps/ias-bingo/shared/ve/local/lib/python2.7/site-packages/twitter/api.py", line 240, in __call__
    body = '\r\n'.join(bod)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)
```

http://stackoverflow.com/questions/9644099/python-ascii-codec-cant-decode-byte

**Comment by tpitale** [comment]
May need to update the twitter library and use a different method … https://github.com/sixohsix/twitter/issues/257

**Comment by tpitale** [comment]
Updating to 1.16.0 of twitter library.

**Comment by tpitale** [comment]
Tada! https://twitter.com/iasBingo/status/588503129685159936

**Comment by livlab** [comment]
Yay!!! Woo hoo. You rock.
