### ISSUE TITLE
Create hashtags and card content for IAS 2015

### ISSUE THREAD

**Issue by livlab** [livlab/ias-bingo#11]
Update in spreadsheet

**Comment by livlab** [comment]
- [x] Updated spreadsheet with sample content
- [x] change CSV file name from nameofscv.csv to iasbingo.csv

**Comment by livlab** [comment]
Sample content is updated in the spreadsheet. I have asked other people to contribute so well have an updated spreadsheet to use closer to the summit. For now, iasbingo.csv is good to be loaded in to DB.

**Comment by tpitale** [comment]
I'll do this in the morning!

**Comment by tpitale** [comment]
I ran the import of the CSV. Not sure how to see if it worked.

**Comment by tpitale** [comment]
Looks like the goals are in the database, so I guess that works!
