### ISSUE TITLE
Direct iasbingo.com to IP

### ISSUE THREAD

**Issue by livlab** [livlab/ias-bingo#20]

**Comment by livlab** [comment]
Hi @tpitale, do you think you'll be able to do this? I was hoping to be ready to test play y no later than next weekend. Let me know if I can help with this part.

**Comment by tpitale** [comment]
Yep! Planning to work on it this week and Saturday.

**Comment by tpitale** [comment]
IP: 104.131.176.194

**Comment by livlab** [comment]
All done. Works!
