### ISSUE TITLE
Set up server

### ISSUE THREAD

**Issue by livlab** [livlab/ias-bingo#8]

**Comment by tpitale** [comment]
@livlab I can take a stab at this this weekend, if you want to assign it to me.

**Comment by livlab** [comment]
w00t, thanks!

**Comment by livlab** [comment]
There's an Amazon S3 bucket set up for this project FYI. Let me know if you need access.

**Comment by tpitale** [comment]
Created the start of a PR #18. I'll keep digging on that.

**Comment by tpitale** [comment]
That PR is done and ready, so I'm closing this.
