### ISSUE TITLE
Test play with twitter.com

### ISSUE THREAD

**Issue by livlab** [livlab/ias-bingo#9]
- [x] request a card
- [ ] submit 1 photo with the wrong hashtag (not on your card)
- [ ] submit 5 consecutive photos with hashtag to make bingo from that card
- [ ] verify messages received from bot after each action
- [ ] verify updates to leaderboard page after each action
- [ ] erase all tweets and images
- [ ] erase play in DB

**Comment by tpitale** [comment]
I also submitted one photo with the right hashtag and it worked.

**Comment by tpitale** [comment]
Should there be tweets replying to my tweets at iasBingo?

**Comment by tpitale** [comment]
http://iasbingo.com/card/tpitale

**Comment by livlab** [comment]
Looks like we are not getting any responses to the tweets (we should), but the game is actually working correctly. I'll investigate tonight.
